use phf::phf_map;
use wimpy_engine::app::input::KeyCode as WK;

pub static KEY_CODES: phf::Map<&'static str,WK> = phf_map! {
    // Letters
    "KeyA" => WK::KeyA,
    "KeyB" => WK::KeyB,
    "KeyC" => WK::KeyC,
    "KeyD" => WK::KeyD,
    "KeyE" => WK::KeyE,
    "KeyF" => WK::KeyF,
    "KeyG" => WK::KeyG,
    "KeyH" => WK::KeyH,
    "KeyI" => WK::KeyI,
    "KeyJ" => WK::KeyJ,
    "KeyK" => WK::KeyK,
    "KeyL" => WK::KeyL,
    "KeyM" => WK::KeyM,
    "KeyN" => WK::KeyN,
    "KeyO" => WK::KeyO,
    "KeyP" => WK::KeyP,
    "KeyQ" => WK::KeyQ,
    "KeyR" => WK::KeyR,
    "KeyS" => WK::KeyS,
    "KeyT" => WK::KeyT,
    "KeyU" => WK::KeyU,
    "KeyV" => WK::KeyV,
    "KeyW" => WK::KeyW,
    "KeyX" => WK::KeyX,
    "KeyY" => WK::KeyY,
    "KeyZ" => WK::KeyZ,

    // Digits
    "Digit0" => WK::Digit0,
    "Digit1" => WK::Digit1,
    "Digit2" => WK::Digit2,
    "Digit3" => WK::Digit3,
    "Digit4" => WK::Digit4,
    "Digit5" => WK::Digit5,
    "Digit6" => WK::Digit6,
    "Digit7" => WK::Digit7,
    "Digit8" => WK::Digit8,
    "Digit9" => WK::Digit9,

    // Arrows
    "ArrowDown" => WK::ArrowDown,
    "ArrowLeft" => WK::ArrowLeft,
    "ArrowRight" => WK::ArrowRight,
    "ArrowUp" => WK::ArrowUp,

    // Other
    "Escape" => WK::Escape,
    "Space" => WK::Space,
    "Tab" => WK::Tab,
    "Minus" => WK::Minus,
    "Equal" => WK::Equal,
    "BracketLeft" => WK::BracketLeft,
    "BracketRight" => WK::BracketRight,
    "Backslash" => WK::Backslash,
    "Backquote" => WK::Backquote,
    "Semicolon" => WK::Semicolon,
    "Quote" => WK::Quote,
    "Comma" => WK::Comma,
    "Period" => WK::Period,
    "Slash" => WK::Slash,
    "AltLeft" => WK::AltLeft,
    "AltRight" => WK::AltRight,
    "ControlLeft" => WK::ControlLeft,
    "ControlRight" => WK::ControlRight,
    "ShiftLeft" => WK::ShiftLeft,
    "ShiftRight" => WK::ShiftRight,
    "Enter" => WK::Enter,
    "Backspace" => WK::Backspace,
    "MetaLeft" => WK::MetaLeft,
    "MetaRight" => WK::MetaRight,
    "ContextMenu" => WK::ContextMenu,
    "CapsLock" => WK::CapsLock,
    "ScrollLock" => WK::ScrollLock,
    "NumLock" => WK::NumLock,
    "Pause" => WK::Pause,
    "PrintScreen" => WK::PrintScreen,
    "Delete" => WK::Delete,
    "End" => WK::End,
    "Help" => WK::Help,
    "Home" => WK::Home,
    "Insert" => WK::Insert,
    "PageDown" => WK::PageDown,
    "PageUp" => WK::PageUp,

    //Function
    "F1" => WK::F1,
    "F2" => WK::F2,
    "F3" => WK::F3,
    "F4" => WK::F4,
    "F5" => WK::F5,
    "F6" => WK::F6,
    "F7" => WK::F7,
    "F8" => WK::F8,
    "F9" => WK::F9,
    "F10" => WK::F10,
    "F11" => WK::F11,
    "F12" => WK::F12,

    // Numpad numbers
    "Numpad0" => WK::Numpad0,
    "Numpad1" => WK::Numpad1,
    "Numpad2" => WK::Numpad2,
    "Numpad3" => WK::Numpad3,
    "Numpad4" => WK::Numpad4,
    "Numpad5" => WK::Numpad5,
    "Numpad6" => WK::Numpad6,
    "Numpad7" => WK::Numpad7,
    "Numpad8" => WK::Numpad8,
    "Numpad9" => WK::Numpad9,

    // Numpad others
    "NumpadAdd" => WK::NumpadAdd,
    "NumpadSubtract" => WK::NumpadSubtract,
    "NumpadMultiply" => WK::NumpadMultiply,
    "NumpadDivide" => WK::NumpadDivide,
    "NumpadDecimal" => WK::NumpadDecimal,
    "NumpadComma" => WK::NumpadComma,
    "NumpadBackspace" => WK::NumpadBackspace,
    "NumpadClear" => WK::NumpadClear,
    "NumpadClearEntry" => WK::NumpadClearEntry,
    "NumpadEnter" => WK::NumpadEnter,
    "NumpadEqual" => WK::NumpadEqual,
    "NumpadHash" => WK::NumpadHash,
    "NumpadParenLeft" => WK::NumpadParenLeft,
    "NumpadParenRight" => WK::NumpadParenRight,
    "NumpadMemoryAdd" => WK::NumpadMemoryAdd,
    "NumpadMemorySubtract" => WK::NumpadMemorySubtract,
    "NumpadMemoryClear" => WK::NumpadMemoryClear,
    "NumpadMemoryStore" => WK::NumpadMemoryStore,
    "NumpadMemoryRecall" => WK::NumpadMemoryRecall,
};
