use wimpy_engine::app::input::KeyCode as WK;
use sdl2::keyboard::Keycode as SK;

pub fn translate_key_code(key_code: SK) -> Option<WK> {
    match key_code {
        // Letters
        SK::A => Some(WK::KeyA),
        SK::B => Some(WK::KeyB),
        SK::C => Some(WK::KeyC),
        SK::D => Some(WK::KeyD),
        SK::E => Some(WK::KeyE),
        SK::F => Some(WK::KeyF),
        SK::G => Some(WK::KeyG),
        SK::H => Some(WK::KeyH),
        SK::I => Some(WK::KeyI),
        SK::J => Some(WK::KeyJ),
        SK::K => Some(WK::KeyK),
        SK::L => Some(WK::KeyL),
        SK::M => Some(WK::KeyM),
        SK::N => Some(WK::KeyN),
        SK::O => Some(WK::KeyO),
        SK::P => Some(WK::KeyP),
        SK::Q => Some(WK::KeyQ),
        SK::R => Some(WK::KeyR),
        SK::S => Some(WK::KeyS),
        SK::T => Some(WK::KeyT),
        SK::U => Some(WK::KeyU),
        SK::V => Some(WK::KeyV),
        SK::W => Some(WK::KeyW),
        SK::X => Some(WK::KeyX),
        SK::Y => Some(WK::KeyY),
        SK::Z => Some(WK::KeyZ),

        // Digits
        SK::NUM_0 => Some(WK::Digit0),
        SK::NUM_1 => Some(WK::Digit1),
        SK::NUM_2 => Some(WK::Digit2),
        SK::NUM_3 => Some(WK::Digit3),
        SK::NUM_4 => Some(WK::Digit4),
        SK::NUM_5 => Some(WK::Digit5),
        SK::NUM_6 => Some(WK::Digit6),
        SK::NUM_7 => Some(WK::Digit7),
        SK::NUM_8 => Some(WK::Digit8),
        SK::NUM_9 => Some(WK::Digit9),

        // Arrows
        SK::DOWN => Some(WK::ArrowDown),
        SK::LEFT => Some(WK::ArrowLeft),
        SK::RIGHT => Some(WK::ArrowRight),
        SK::UP => Some(WK::ArrowUp),

        // Other
        SK::ESCAPE => Some(WK::Escape),
        SK::SPACE => Some(WK::Space),
        SK::TAB => Some(WK::Tab),
        SK::MINUS => Some(WK::Minus),
        SK::EQUALS => Some(WK::Equal),
        SK::LEFTBRACKET => Some(WK::BracketLeft),
        SK::RIGHTBRACKET => Some(WK::BracketRight),
        SK::BACKSLASH => Some(WK::Backslash),
        SK::BACKQUOTE => Some(WK::Backquote),
        SK::SEMICOLON => Some(WK::Semicolon),
        SK::QUOTE => Some(WK::Quote),
        SK::COMMA => Some(WK::Comma),
        SK::PERIOD => Some(WK::Period),
        SK::SLASH => Some(WK::Slash),
        SK::LALT => Some(WK::AltLeft),
        SK::RALT => Some(WK::AltRight),
        SK::LCTRL => Some(WK::ControlLeft),
        SK::RCTRL => Some(WK::ControlRight),
        SK::LSHIFT => Some(WK::ShiftLeft),
        SK::RSHIFT => Some(WK::ShiftRight),
        SK::RETURN => Some(WK::Enter),
        SK::BACKSPACE => Some(WK::Backspace),
        SK::LGUI => Some(WK::MetaLeft),
        SK::RGUI => Some(WK::MetaRight),
        SK::APPLICATION => Some(WK::ContextMenu),
        SK::CAPSLOCK => Some(WK::CapsLock),
        SK::SCROLLLOCK => Some(WK::ScrollLock),
        SK::NUMLOCKCLEAR => Some(WK::NumLock),
        SK::PAUSE => Some(WK::Pause),
        SK::PRINTSCREEN => Some(WK::PrintScreen),
        SK::DELETE => Some(WK::Delete),
        SK::END => Some(WK::End),
        SK::HELP => Some(WK::Help),
        SK::HOME => Some(WK::Home),
        SK::INSERT => Some(WK::Insert),
        SK::PAGEDOWN => Some(WK::PageDown),
        SK::PAGEUP => Some(WK::PageUp),

        // Function
        SK::F1 => Some(WK::F1),
        SK::F2 => Some(WK::F2),
        SK::F3 => Some(WK::F3),
        SK::F4 => Some(WK::F4),
        SK::F5 => Some(WK::F5),
        SK::F6 => Some(WK::F6),
        SK::F7 => Some(WK::F7),
        SK::F8 => Some(WK::F8),
        SK::F9 => Some(WK::F9),
        SK::F10 => Some(WK::F10),
        SK::F11 => Some(WK::F11),
        SK::F12 => Some(WK::F12),

        // Numpad numbers
        SK::KP_0 => Some(WK::Numpad0),
        SK::KP_1 => Some(WK::Numpad1),
        SK::KP_2 => Some(WK::Numpad2),
        SK::KP_3 => Some(WK::Numpad3),
        SK::KP_4 => Some(WK::Numpad4),
        SK::KP_5 => Some(WK::Numpad5),
        SK::KP_6 => Some(WK::Numpad6),
        SK::KP_7 => Some(WK::Numpad7),
        SK::KP_8 => Some(WK::Numpad8),
        SK::KP_9 => Some(WK::Numpad9),

        // Numpad others
        SK::KP_PLUS => Some(WK::NumpadAdd),
        SK::KP_MINUS => Some(WK::NumpadSubtract),
        SK::KP_MULTIPLY => Some(WK::NumpadMultiply),
        SK::KP_DIVIDE => Some(WK::NumpadDivide),
        SK::KP_DECIMAL => Some(WK::NumpadDecimal),
        SK::KP_COMMA => Some(WK::NumpadComma),
        SK::KP_BACKSPACE => Some(WK::NumpadBackspace),
        SK::KP_CLEAR => Some(WK::NumpadClear),
        SK::KP_CLEARENTRY => Some(WK::NumpadClearEntry),
        SK::KP_ENTER => Some(WK::NumpadEnter),
        SK::KP_EQUALS => Some(WK::NumpadEqual),
        SK::KP_HASH => Some(WK::NumpadHash),
        SK::KP_LEFTPAREN => Some(WK::NumpadParenLeft),
        SK::KP_RIGHTPAREN => Some(WK::NumpadParenRight),
        SK::KP_MEMADD => Some(WK::NumpadMemoryAdd),
        SK::KP_MEMSUBTRACT => Some(WK::NumpadMemorySubtract),
        SK::KP_MEMCLEAR => Some(WK::NumpadMemoryClear),
        SK::KP_MEMSTORE => Some(WK::NumpadMemoryStore),
        SK::KP_MEMRECALL => Some(WK::NumpadMemoryRecall),

        _ => None //Key not supported
    }
}
